#!/usr/bin/env bash
# Regenerate qsb_carrier_sm89.h, the native sm_89 image that QsbCarrier.h loads.
# Development tool, never run by the ranked harness. Rerun after ANY edit to
# pinning.cu or a header it includes, with the same CUDA toolkit as the runner (12.8).
#   ./build_carrier.sh [QSB_ZEROS_N]
set -euo pipefail
cd "$(dirname "$0")"
Z=${1:-24}
W=$(mktemp -d)   # logs and the raw cubin stay out of the submission directory
nvcc -O3 -DQSB_ZEROS_N="$Z" -DQSB_CARRIER_BUILD=1 -arch=sm_89 -cubin \
     -Xptxas -v -o "$W/c.cubin" pinning.cu 2> "$W/ptxas.log"
cuobjdump -symbols "$W/c.cubin" > "$W/symbols.txt"
cuobjdump -sass "$W/c.cubin" > "$W/sass.txt"
python3 - "$Z" "$W" <<'PY'
import base64, hashlib, re, sys
zeros = int(sys.argv[1]); W = sys.argv[2]
syms = open(W + "/symbols.txt").read()
want = [  # order must match enum QsbCarrierKernel in QsbCarrier.h
    ("QK_S0",    r"_Z23kernel_pinning_pipelineILb1ELi0EE\w+"),
    ("QK_S2",    r"_Z23kernel_pinning_pipelineILb1ELi2EE\w+"),
    ("QK_RGP",   r"_Z22qsb_root_group_prepare\w+"),
    ("QK_ISR",   r"_Z22qsb_invert_super_roots\w+"),
    ("QK_RGF",   r"_Z21qsb_root_group_finish\w+"),
    ("QK_BUILD", r"_Z19kernel_build_gtable\w+"),
    ("QK_YOFF",  r"_Z18qsb_table_offset_y\w+"),
]
names = []
for kid, pat in want:
    hits = sorted(set(re.findall(pat, syms)))
    if len(hits) != 1:
        sys.exit(f"build_carrier: {kid} matched {hits}")
    names.append(hits[0])
for g in ("qsb_carrier_zeros", "pin_u2rx_words", "pin_u2ry_words", "pin_iso_invu_words",
          "pin_iso_u2ry_words", "pin_iso_xneg", "pin_recovery_c", "pin_u2rk_words",
          "pin_one_mul", "pin_zero_add", "pin_tail_words"):
    if not re.search(r"\b%s\b" % g, syms):
        sys.exit(f"build_carrier: global {g} missing from image")
# The hint must be present in the prepare kernel (the only table reader on the hot path).
sass = open(W + "/sass.txt").read()
fn = re.split(r"\n\s*Function : ", sass)
s0 = [b for b in fn if b.startswith(names[0])]
if not s0 or "LTC64B" not in s0[0]:
    sys.exit("build_carrier: prepare kernel has no LDG.E.LTC64B load")
n_hint = s0[0].count("LTC64B")
img = open(W + "/c.cubin", "rb").read()
b64 = base64.b64encode(img).decode()
lines = [b64[i:i + 120] for i in range(0, len(b64), 120)]
sha = hashlib.sha256(img).hexdigest()
with open("qsb_carrier_sm89.h", "w") as f:
    f.write("/* GENERATED by build_carrier.sh -- do not edit. Native sm_89 image of pinning.cu\n")
    f.write(f" * built with -DQSB_CARRIER_BUILD=1 -DQSB_ZEROS_N={zeros} -arch=sm_89.\n")
    f.write(f" * cubin sha256 {sha}; {len(img)} bytes; prepare kernel LTC64B loads: {n_hint}. */\n")
    f.write("#pragma once\n#include <stddef.h>\n")
    f.write(f"static const size_t qsb_carrier_cubin_bytes = {len(img)};\n")
    f.write(f'static const char qsb_carrier_cubin_sha256[] = "{sha}";\n')
    f.write("static const char *const qsb_carrier_kernel_names[] = {\n")
    for kid, n in zip([k for k, _ in want], names):
        f.write(f'    "{n}", /* {kid} */\n')
    f.write("};\n")
    f.write(f"static const unsigned qsb_carrier_b64_lines = {len(lines)};\n")
    f.write("static const char *const qsb_carrier_b64[] = {\n")
    for l in lines:
        f.write(f'"{l}",\n')
    f.write("};\n")
print(f"qsb_carrier_sm89.h: {len(img)} B cubin, sha256 {sha[:16]}, {len(lines)} lines, LTC64B loads in prepare: {n_hint}")
PY
grep -E "Function properties for _Z23kernel_pinning_pipelineILb1ELi[02]|registers" "$W/ptxas.log" | grep -A1 "kernel_pinning_pipelineILb1" | head -8 || true
echo "build logs: $W"
