#!/usr/bin/env bash
# Build a pinning variant whose embedded native sm_89 image comes from clang's
# CUDA frontend (LLVM NVPTX -> PTX) assembled by CUDA 12.8 ptxas, instead of nvcc.
#
#   make_clang_variant.sh <out-dir> [clang++-version-binary] [extra clang flags...]
#
# The ranked runner still compiles pinning.cu with nvcc; only the embedded
# image (data in qsb_carrier_sm89.h) changes. The header is generated by the
# exact Python block of candidates/pinning/build_carrier.sh, so symbol checks,
# LTC64B check and header format are identical to the nvcc path.
set -euo pipefail
LAB="$(cd "$(dirname "$0")" && pwd)"; SRC="$(dirname "$LAB")/candidates/pinning"
OUT=$1; CLANG=${2:-clang++-18}; shift $(( $# > 1 ? 2 : 1 )); EXTRA=("$@")
CUDA=${CUDA_PATH:-/usr/local/cuda-12.8}; export PATH="$CUDA/bin:$PATH"
Z=24

rm -rf "$OUT"; mkdir -p "$(dirname "$OUT")"; cp -r "$SRC" "$OUT"; cd "$OUT"
W=$(mktemp -d)
# -inline-threshold: clang otherwise leaves _FixedBaseSignedXYZZScalar as a real
# call and passes z and the four output coordinates through a 160-byte stack frame.
"$CLANG" -x cuda --cuda-path="$CUDA" --cuda-gpu-arch=sm_89 --cuda-device-only -S -O3 \
  -DQSB_ZEROS_N=$Z -DQSB_CARRIER_BUILD=1 -Wno-unknown-cuda-version -Wno-deprecated-declarations \
  -mllvm -inline-threshold=100000 "${EXTRA[@]}" -o "$W/c.ptx" pinning.cu
ptxas -O3 -arch=sm_89 -v -o "$W/c.cubin" "$W/c.ptx" 2> "$W/ptxas.log"
cuobjdump -symbols "$W/c.cubin" > "$W/symbols.txt"
cuobjdump -sass "$W/c.cubin" > "$W/sass.txt"
# Reuse build_carrier.sh's generator verbatim (it reads $W/{c.cubin,symbols.txt,sass.txt}).
eval "$(sed -n '/^python3 - "\$Z" "\$W" <<.PY.$/,/^PY$/p' build_carrier.sh)"
sed -i "1s|.*|/* GENERATED by .gpu-lab/make_clang_variant.sh ($("$CLANG" --version | head -1)) + ptxas $(ptxas --version | sed -n 's/.*release \([0-9.]*\).*/\1/p'). Native sm_89 image of pinning.cu|" qsb_carrier_sm89.h
grep -A2 -E "Function properties for _Z23kernel_pinning_pipelineILb1ELi[02]" "$W/ptxas.log" | grep -E 'stack|Used' || true
rm -rf "$W"
